// InvoiceForge profession template presets — generated by gen_invoiceforge_templates.py.
// Source of truth for the ?tpl= prefill in index.html.
window.INVOICEFORGE_PRESETS = {
  "photographer": {
    label: "Photographer",
    biz: "Your Name — Photography",
    notes: "Payment due within 14 days. A 50% deposit reserves the date; the balance is due on delivery of the gallery.",
    items: [["Engagement session", 1, 350], ["Wedding day coverage (8 hrs)", 1, 2400], ["Photo editing & retouching", 40, 25]]
  },
  "consultant": {
    label: "Consultant",
    biz: "Your Name — Consulting",
    notes: "Payment due within 14 days. Reimbursable expenses are listed net of any deposit.",
    items: [["Strategy consulting", 12, 150], ["Workshop facilitation", 3, 600], ["Travel expenses (reimbursable)", 1, 240]]
  },
  "contractor": {
    label: "Contractor",
    biz: "Your Name — Contracting",
    notes: "Payment due within 14 days. Change orders are billed separately and require written approval.",
    items: [["Labor (carpentry)", 40, 65], ["Materials", 1, 1850], ["Equipment rental", 3, 95]]
  },
  "plumber": {
    label: "Plumber",
    biz: "Your Name — Plumbing",
    notes: "Payment due on receipt. After-hours rates are 1.5× the standard rate.",
    items: [["Service call", 1, 89], ["Labor (2 hrs)", 2, 95], ["Parts & materials", 1, 120]]
  },
  "electrician": {
    label: "Electrician",
    biz: "Your Name — Electrical",
    notes: "Payment due within 14 days. Permit fees are passed through at cost.",
    items: [["Service call", 1, 89], ["Labor (3 hrs)", 3, 90], ["Panel & breaker materials", 1, 450]]
  },
  "cleaning": {
    label: "Cleaning service",
    biz: "Your Name — Cleaning Services",
    notes: "Payment due within 14 days. Recurring clients are billed monthly.",
    items: [["Deep clean (1,800 sq ft)", 1, 220], ["Window cleaning (interior)", 12, 8], ["Cleaning supplies", 1, 25]]
  },
  "landscaper": {
    label: "Landscaper",
    biz: "Your Name — Landscaping",
    notes: "Payment due within 14 days. Maintenance is billed monthly in arrears.",
    items: [["Weekly mowing (4 visits)", 4, 45], ["Hedge trimming", 2, 60], ["Mulch & flower bed install", 1, 380]]
  },
  "graphic-designer": {
    label: "Graphic designer",
    biz: "Your Name — Design",
    notes: "Payment due within 14 days. A 50% deposit was required to begin; the balance is due on delivery of final files.",
    items: [["Logo design", 1, 600], ["Brand guidelines", 1, 400], ["Additional revisions", 3, 75]]
  },
  "web-developer": {
    label: "Web developer",
    biz: "Your Name — Web Development",
    notes: "Payment due within 14 days. 50% deposit required to begin; balance due on launch.",
    items: [["Website build (fixed price)", 1, 3200], ["Hosting & domain setup", 1, 150], ["Monthly maintenance", 1, 120]]
  },
  "virtual-assistant": {
    label: "Virtual assistant",
    biz: "Your Name — Virtual Assistant",
    notes: "Payment due within 14 days. Monthly retainer covers 20 hours; additional hours billed at the standard rate.",
    items: [["Email & calendar management", 20, 35], ["Data entry", 10, 30], ["Social media scheduling", 8, 40]]
  },
  "tutor": {
    label: "Tutor",
    biz: "Your Name — Tutoring",
    notes: "Payment due within 14 days. Sessions cancelled with less than 24 hours’ notice are billed in full.",
    items: [["One-on-one tutoring (10 sessions)", 10, 55], ["Lesson materials", 1, 40]]
  },
  "writer": {
    label: "Freelance writer",
    biz: "Your Name — Writing",
    notes: "Payment due within 14 days. Rates are per the signed brief; additional rounds billed at the hourly rate.",
    items: [["Blog post (1,500 words)", 1, 450], ["Copy editing", 1, 300], ["Research", 4, 60]]
  },
  "handyman": {
    label: "Handyman",
    biz: "Your Name — Handyman Services",
    notes: "Payment due on receipt. One-hour minimum applies; materials billed at cost.",
    items: [["Service call / trip charge", 1, 45], ["Labor (2.5 hrs)", 3, 55], ["Materials (shelf, anchors)", 1, 38]]
  },
  "painter": {
    label: "Painter",
    biz: "Your Name — Painting",
    notes: "Payment due within 14 days. A 30% deposit was required to schedule; balance due on completion.",
    items: [["Interior painting (3 rooms)", 1, 1400], ["Prep & patching", 8, 40], ["Paint & supplies", 1, 260]]
  },
  "hvac": {
    label: "HVAC technician",
    biz: "Your Name — HVAC",
    notes: "Payment due within 14 days. Diagnostic fee is credited toward approved repairs.",
    items: [["Service call / diagnostic", 1, 89], ["Labor (2 hrs)", 2, 95], ["Capacitor & parts", 1, 180]]
  },
  "roofer": {
    label: "Roofer",
    biz: "Your Name — Roofing",
    notes: "Payment due within 14 days. A deposit was required to order materials; balance due on completion.",
    items: [["Roof replacement (24 squares)", 24, 350], ["Tear-off & disposal", 1, 900], ["Permits", 1, 250]]
  },
  "locksmith": {
    label: "Locksmith",
    biz: "Your Name — Locksmith",
    notes: "Payment due on receipt. After-hours callouts billed at the emergency rate.",
    items: [["Service call", 1, 65], ["Rekey (3 locks)", 3, 30], ["New deadbolt", 1, 85]]
  },
  "mover": {
    label: "Moving company",
    biz: "Your Name — Moving Services",
    notes: "Payment due on completion. A deposit was required to reserve the truck and crew.",
    items: [["Crew labor (2 movers, 5 hrs)", 10, 60], ["Travel time", 1, 60], ["Packing supplies", 1, 140]]
  },
  "personal-trainer": {
    label: "Personal trainer",
    biz: "Your Name — Personal Training",
    notes: "Payment due within 14 days. Sessions cancelled with less than 24 hours notice are billed in full.",
    items: [["Personal training (8 sessions)", 8, 60], ["Custom program design", 1, 120]]
  },
  "hair-stylist": {
    label: "Hair stylist",
    biz: "Your Name — Hair Styling",
    notes: "Payment due on receipt. A deposit is required for event and wedding bookings.",
    items: [["Cut & color", 1, 180], ["Deep-conditioning treatment", 1, 40], ["Products", 1, 35]]
  },
  "makeup-artist": {
    label: "Makeup artist",
    biz: "Your Name — Makeup Artistry",
    notes: "Payment due within 14 days. A deposit reserves the date; balance due on the event day.",
    items: [["Bridal makeup", 1, 250], ["Trial session", 1, 120], ["Kit fee", 1, 40]]
  },
  "dj": {
    label: "DJ",
    biz: "Your Name — DJ & Entertainment",
    notes: "Payment due within 14 days. A deposit reserves the date; balance due on the event day.",
    items: [["Wedding reception (5 hrs)", 1, 950], ["Lighting package", 1, 150], ["Overtime (1 hr)", 1, 100]]
  },
  "bookkeeper": {
    label: "Bookkeeper",
    biz: "Your Name — Bookkeeping",
    notes: "Payment due within 14 days. Retainer covers the stated month; catch-up work billed separately.",
    items: [["Monthly bookkeeping retainer", 1, 350], ["Catch-up (3 months)", 3, 120], ["Software (QuickBooks)", 1, 60]]
  },
  "caterer": {
    label: "Caterer",
    biz: "Your Name — Catering",
    notes: "Payment due within 14 days. A deposit confirms the date and final headcount; balance due after the event.",
    items: [["Dinner service (60 guests)", 60, 55], ["Service staff (4)", 4, 150], ["Rentals & linens", 1, 380]]
  },
};
